name: ECS CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 052423658228.dkr.ecr.eu-central-1.amazonaws.com/my-ecr
          aws-region: eu-central-1
      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: 052423658228.dkr.ecr.eu-central-1.amazonaws.com/my-ecr
          ECR_REPOSITORY: my-ecr
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Update ECS Service
        id: update-service
        env:
          AWS_ACCESS_KEY_ID: AKIAQYNFRRL2NBE5ONWQ
          AWS_SECRET_ACCESS_KEY: 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
          ECS_CLUSTER_NAME: my-cluster1
          ECS_SERVICE_NAME: my-service
          TASK_DEFINITION_FAMILY: task-def
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        uses: einaregilsson/ecs-deploy@v20.3.0
        with:
          access_key_id: AKIAQYNFRRL2NBE5ONWQ
          secret_access_key: 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
          region: eu-central-1
          cluster: my-cluster1
          service: my-service
          task_definition_family: task-def
          image_tag: ${{ env.IMAGE_TAG }}
